### ISSUE TITLE
Bot Token

### ISSUE THREAD

**Issue by robotrono** [Adure/discord-colour-changing-bot#1]
Hello, I'm new in python sorry but where I can set the bot token?
Sorry for my bad english.

**Comment by Adure** [comment]
in `client.run()`

**Comment by robotrono** [comment]
Thanks for the response, I get this error:
`ImportError: cannot import name 'bot_token' from 'auth' (C:\Python3\lib\site-packages\auth\__init__.py)`

**Comment by robotrono** [comment]
```
E:\bot>python color.py
Traceback (most recent call last):
  File "color.py", line 5, in <module>
    from auth import bot_token
ImportError: cannot import name 'bot_token'
```
I set the bot token in `client.run('token')`

**Comment by robotrono** [comment]
Thanks for the response @Adure, I set the bot token in client.run('token') but I get this error:

E:\bot>python color.py
Traceback (most recent call last):
  File "color.py", line 5, in <module>
    from auth import bot_token
ImportError: cannot import name 'bot_token'

**Comment by Adure** [comment]
auth is just the file I have my bot token in, you need to get your own token from https://discordapp.com/developers/applications/

**Comment by robotrono** [comment]
@Adure done, so I need remove "from auth import bot_token" and works fine?

**Comment by Adure** [comment]
yep

**Comment by robotrono** [comment]
Now I get this Q_Q: 

```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "color.py", line 38, in on_ready
    await client.edit_role(flash_server, flash_role, colour=colours[colour_index])
  File "C:\Python3\lib\site-packages\discord\client.py", line 2860, in edit_role
    yield from self.http.edit_role(server.id, role.id, **payload)
  File "C:\Python3\lib\site-packages\discord\http.py", line 196, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions
```

**Comment by Adure** [comment]
You need to enter your own server and role id and the bot's role needs to be higher than the role you're trying to change

**Comment by robotrono** [comment]
Thanks now works fine!
